# Generated by Django 4.1.6 on 2023-02-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promo_marketing',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
    ]
